### ISSUE TITLE
"source_id" parameter

### ISSUE THREAD

**Issue by marcopasi** [Multiscale-Genomics/mg-dm-api#6]
The method parameter corresponding to the "source_id" entry in the file object should be named "source_id" for consistency. This is the case for all methods except "dmp.set_file", where it is "source" (https://github.com/Multiscale-Genomics/mg-dm-api/blob/master/dmp/dmp.py#L391):

```python
[...]
def set_file(self, user_id, file_path, file_type = "", data_type = "", taxon_id = "", compressed=None, source = [], meta_data = {}, **kwargs):
[...] 
```
I propose to change it to "source_id".

**Comment by markmcdowall** [comment]
I have added this to the code
